### ISSUE TITLE
Pregled informacija o pacijentu

### ISSUE THREAD

**Issue by deancupovic** [SoftverInzenjeringETFSA/SI2014Tim12#11]
Pregled informacija o pacijentu - ako niste već napisali šta se prikazuje, što se niste referirali na prethodno poglavlje u kojem se opisuje šta se unosi za pacijenta.

**Comment by luka454** [comment]
Ispravljeno dodani su izlazni podaci iz prethodih poglavlja: Ime i prezime, Datum rođenja, Broj telefona,  Dodatne informacije(opis),
te još su dodani i sve posjete pacijenta, i svi zakazani termini pacijenta
