### ISSUE TITLE
3.2.1.5 (pacijent info)

### ISSUE THREAD

**Issue by deancupovic** [SoftverInzenjeringETFSA/SI2014Tim12#12]
Zašto ovo nije u sklopu pacijenta.

**Comment by luka454** [comment]
Mislite 3.2.2.5 dodatne informacije o pacijentu?
Ovo je ispravljeno i Dodatne informacije(opis) su dodane u 3.2.2.1 Registraciji novog pacijenta, 3.2.2.2 Modifikacija podataka pacijenta
