### ISSUE TITLE
*.hbm.xml

### ISSUE THREAD

**Issue by deancupovic** [SoftverInzenjeringETFSA/SI2014Tim12#24]
Prebacite sve mapping fajlove *.hbm.xml u src/main/resources i ažurirajte hibernate.cfg.xml.

JUnit ne može da ih nađe, a kada ih stavite u resources folder, onda može.

**Comment by luka454** [comment]
Pokušao sam sve živo, međutim ukoliko to uradim onda niti maven niti eclipse ne mogu naći te file-ove.
hibernate.cfg.xml kao da vidi samo file-ove unutar /src/main/java, iz ne znam kojeg razloga. Čak sam i u pom.xml dodao resurse na direktori /src/main/java, ali ni to ne pomaže. 
Ukoliko postavljam preko GUI-a ponudi samo java foldere: http://pokit.org/get/?651497713b34afe56ef2e46d4a62227e.jpg
A ručno sam unio pathove: http://pokit.org/get/?ea53810ed5e662e120af1c825aa60fc6.jpg
Ali ih svejedno ne pronalazi

**Comment by deancupovic** [comment]
Ja sam također pokušao i uspio.
Dakle stavite ih u isti folder gdje je i hibernate.cfg.xml,
U hibernate.cfg.xml ostavite reference na njih bez putanja, dakle samo "Korisnik.hbm.xml". Možete ući ručno u XML tekst editorom i promjeniti. U tom slučaju maven testovi prolaze.
Također ako prebacujete file izvan eclispe, posliej toga uradite refresh projekta.

**Comment by luka454** [comment]
Eee radi ovako bez putanje :D Hvala Vam :D
