### ISSUE TITLE
UTF-8

### ISSUE THREAD

**Issue by deancupovic** [SoftverInzenjeringETFSA/SI2014Tim12#25]
Pretvorite encoding svih fajlova u UTF-8.
Npr.
src\test\java\ba\unsa\etf\si\tim12\dal\domainmodel\KorisnikTest.java
je ANSI encoding

**Comment by luka454** [comment]
Popravljeno je u Eclipse, ne znam hoće li se to odraziti na projekt.
U pom.xml također su dodani neki ecodinzi, ne znam kako provjeriti da li to radi ispravno
