### ISSUE TITLE
Neočekivani Error Message pri zatvaranju Pregleda termina

### ISSUE THREAD

**Issue by FarukLjuca** [SoftverInzenjeringETFSA/SI2014Tim12#27]
Komponenta:
Forma - Pregled termina

Commit ID:
9e776b20e3a1193cdb2122cd9637f3d014c0839d

Opis problema:
Zatvaranje forme Pregled termina daje neočekivan Error Message sadržaja: "Pacijent s ID-om: 0 nije pronađen" i naslova: "nesto"

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "Zubarska ordinacija"
2. Logiranje
3. Izbor taba Termini
4. Klik na dugme pregled termina
5. Klik na dogme Close (gornji desni ćošak)

Dobijeni rezultat:
- Pojava Error Message-a sadržaja: "Pacijent s ID-om: 0 nije pronađen" i naslova: "nesto"
  ![screenshot_1](https://cloud.githubusercontent.com/assets/11351969/7821650/8e7c381e-03f0-11e5-9b5e-779ed4d87fc5.png)

Očekivani rezultat:
- Očekuje se zatvaranje forme bez pojave Message Box-a, zato što zatvaranje forme ne treba davati ikakvu prijavu greške

**Comment by SumejjaPorca** [comment]
Ispravljeno.
