### ISSUE TITLE
Greška pri validaciji polja 'Vrijeme' u procesu zakazivanja termina

### ISSUE THREAD

**Issue by AdnanLFC** [SoftverInzenjeringETFSA/SI2014Tim12#28]
Komponenta:
RezervacijaTerminaGUI.java

Commit ID:
9e776b20e3a1193cdb2122cd9637f3d014c0839d

Opis problema:
U polje 'Vrijeme' je moguće unijeti vrijednost koja nije u skladu s predviđenim formatom 'hh:mm'.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju prema uputstvu;
2. Izvršiti prijavu;
3. Na glavnom izborniku izabrati opciju 'Termini', a nakon toga opciju 'Rezervacija termina';
4. Odabrati nekog od prethodno kreiranih pacijenata;
5. Unijeti neku vrijednost u polje 'Doktor', npr. 'Dr. Who';
6. U polje 'Datum' unijeti vrijednost '666:666';
7. Izabrati neki datum i kliknuti na dugme 'Registruj novi termin';

Dobijeni rezultat:
Potvrda da je termin uspješno registriran.

Očekivani rezultat:
Upozorenje (obavještenje o greški) da polje 'Datum' nije u skladu s predviđenim formatom 'hh:mm'.

**Comment by EnilPajic** [comment]
Popravljeno, _commit ID:_ b693d691c35f9802780c736f539a1e390a8c620d
