### ISSUE TITLE
Nemoguća modofikacija cjene zahvata na decimalan broj

### ISSUE THREAD

**Issue by FarukLjuca** [SoftverInzenjeringETFSA/SI2014Tim12#30]
Komponenta:
Forma - Modifikacija cjene zahvata

Commit ID:
9e776b20e3a1193cdb2122cd9637f3d014c0839d

Opis problema:
Nakon što se unese zahvat, njegova cijena se više ne moše promjeniti na decimalnu vrijednost, a mogla se postaviti na decimalan broj pri dodavanju. Aplikacija "baca" NumberFormatException.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "Zubarska ordinacija"
2. Logiranje
3. Izbor taba zahvati
4. Dodavanje novog zahvata sa validnim podacima ili postojanje već dodanog zahvata
5. Klik na dugme prikaz zahvata
6. Klik na dugme Pretraži kako bi dobili sve zahvate
7. Izbor proizvoljnog zahvata
8. Klik na dugme "Izmjeni cjenu za zahvat"
9. Postavljanje cijene na novi decimalni broj
10. Klik na dugme "Izmjeni"

Dobijeni rezultat:
- Na GUI-u se ništa ne dešava, dok aplikacija u pozadini "baca" NumberFormatException čiji je stack trace naveden ispod u Dodatne informacije

Očekivani rezultat:
- Očekuje se uspješna promjena cijene zahvata

Dodatne informacije:
- Stack trace:
  http://pastebin.com/Bx9H10DE

**Comment by luka454** [comment]
Ispravljeno.

commit ID 7b9190b14862b26bed69bc1ac66c64957868ff6d
