### ISSUE TITLE
Greška u izvještaju o posjetama pacijenta

### ISSUE THREAD

**Issue by AdnanLFC** [SoftverInzenjeringETFSA/SI2014Tim12#31]
Komponenta:
IzvjestajPacijent.java

Commit ID:
60196889e0646bff93fc80fbee18dcc4e1b07f62

Opis problema:
Izvještaj o obavljenim posjetama pacijenta prikazuje samo broj ukupnih posjeta za određenog pacijenta, ali ne i detaljne tabelarne rezultate.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju prema uputstvu;
2. Izvršiti prijavu;
3. Na glavnom izborniku izabrati opciju 'Izvještaji', a nakon toga kliknuti na dugme 'O posjetama pacijenta';
4. Odabrati nekog od prethodno kreiranih pacijenata i kliknuti na dugme 'Prikaži'.

Dobijeni rezultat:
http://i.imgur.com/bHfLGzY.png (za sljedeće unose posjeta: http://i.imgur.com/CtrXifK.png).

Očekivani rezultat:
Detaljan prikaz rezultata u tabeli.

**Comment by SumejjaPorca** [comment]
Ispravljeno.
