### ISSUE TITLE
Nefunkcionalna forma Izvještaj o posjetama po danu

### ISSUE THREAD

**Issue by FarukLjuca** [SoftverInzenjeringETFSA/SI2014Tim12#32]
Komponenta:
Forma - Izvještaj o posjetama po danu

Commit ID:
9e776b2

Pod-Issue:
Imena dugmeta kojim se forma poziva i sama funcija i naziv forme nisu usaglašeni.

Opis problema:
Nakon što se unese nova posjeta na određeni dan, pokuša se dobiti Izvještaj o posjetama po danu i isti se ne dobije tj. ništa se ne dešava u GUI dijelu, dok u pozadnini aplikacija "baca" SQLWarning na nepravilan datum za funkciju str_to_date.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "Zubarska ordinacija"
2. Logiranje
3. Izbor taba posjete
4. Dodavanje nove posjete sa validnim podacima ili postojanje već dodanog zahvata (slika u Dodatne informacije)
5. Izbor taba izvjestaji
6. Klik na dugme O dnevnim/sedmičnim/mjesečnim posjetama
7. Izbor identičnog datuma kao onog kad je posjeta dodana
8. Klik na dugme Prikaži

Dobijeni rezultat:
Na GUI-u se ništa ne dešava (slika u Dodatne informacije), dok aplikacija u pozadini "baca" SQLWarning na nepravilan datum za funkciju str_to_date čiji je stack trace naveden ispod u Dodatne informacije.

Očekivani rezultat:
Očekuje se uspješno dobijanje izvještaja.

Dodatne informacije:
- Stack trace:
  http://pastebin.com/euupHA7f

-Propratne slike:
Slika 1 - Unos nove posjete
![screenshot_3](https://cloud.githubusercontent.com/assets/11351969/7823355/35507812-03fb-11e5-9314-1e303b40a2b8.png)

Slika 2 - Izbor datuma na formi Izvještaj o posjetama po danu
![screenshot_4](https://cloud.githubusercontent.com/assets/11351969/7823407/88745d88-03fb-11e5-8f80-6480fefd1700.png)

**Comment by SumejjaPorca** [comment]
Ispravljeno
