### ISSUE TITLE
Greška u finansijskom izvještaju o svim ulazima

### ISSUE THREAD

**Issue by AdnanLFC** [SoftverInzenjeringETFSA/SI2014Tim12#33]
Komponenta:
IzvjestajUlazi.java

Commit ID:
b1a8fb1949910df6e5bf3e9f12fe8229ceb30a67

Opis problema:
Finansijski izvještaj o svim ulazima ne prikazuje nikakve rezultate bez obzira na odabrani vremenski interval i prethodno unesene podatke (materijale, zahvate, posjete, pacijente, termine, itd.).

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju prema uputstvu;
2. Izvršiti prijavu;
3. Na glavnom izborniku izabrati opciju 'Izvještaji', a nakon toga kliknuti na dugme 'O svim ulazima';
4. Odabrati vremenski interval i kliknuti na dugme 'Prikaži'.

Dobijeni rezultat:
org.hibernate.QueryException (http://i.imgur.com/YIWHWM6.png).

Očekivani rezultat:
Detaljan prikaz rezultata u tabeli.

**Comment by SumejjaPorca** [comment]
Rijeseno
