### ISSUE TITLE
Greška u izvještaju o posjetama i zahvatima

### ISSUE THREAD

**Issue by AdnanLFC** [SoftverInzenjeringETFSA/SI2014Tim12#34]
Komponenta:
IzvjestajPosjeteZahvati.java

Commit ID:
3164aa8d2a691fb6247033d94945bebbe143c67e

Opis problema:
Izvještaj o posjetama i zahvatima ne prikazuje nikakve rezultate bez obzira na odabrani vremenski interval, ime doktora i prethodno unesene podatke (materijale, zahvate, posjete, pacijente, termine, itd.).

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju prema uputstvu;
2. Izvršiti prijavu;
3. Na glavnom izborniku izabrati opciju 'Izvještaji', a nakon toga kliknuti na dugme 'O posjetama i zahvatima';
4. Unijeti ime doktora koje je prethodno korišteno u procesima rezervacije termina i registracije posjete, odabrati vremenski interval i kliknuti na dugme 'Prikaži'.

Dobijeni rezultat:
org.hibernate.QueryException (http://i.imgur.com/tGlq3Xo.png).

Očekivani rezultat:
Detaljan prikaz rezultata u tabeli.

**Comment by SumejjaPorca** [comment]
Rijeseno.
