### ISSUE TITLE
U polje mjerna jedinica materijala se može unjeti bilo šta

### ISSUE THREAD

**Issue by FarukLjuca** [SoftverInzenjeringETFSA/SI2014Tim12#37]
Komponenta:
Forma - Dodavanje novog materijala

Commit ID:
9e776b20e3a1193cdb2122cd9637f3d014c0839d

Opis problema:
U formi dodavanje novog materijala je u polje Mjerna jedinica (JComboBox) moguće unjeti bilo šta tako što se ponuđeni izbor obriše i upiše bilo kakav string.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "Zubarska ordinacija"
2. Logiranje
3. Izbor taba Materijali
4. Klik na dugme dodavanje materijala
5. Unos svih podataka validno sem Mjerne jedinice
6. Obrisati ponuđeni izbor
7. Unjeti proizvoljan string (npr. GRESKA (slika u Dodatnim informacijama))
8. Klik na dugme Kreiraj

Dobijeni rezultat:
- Kreiranje je uspjesno zavrseno i proizvoljni string je priznat

Očekivani rezultat:
- Očekuje se prijava greške jer nije odabrana jedna od ponuđenih mjernih jedinica

Dodatne informacije:

Slika 1 - kreiranje novog materijala
![screenshot_5](https://cloud.githubusercontent.com/assets/11351969/7824712/6fa85d36-0405-11e5-95cd-5c14be7d9ec3.png)

Slika 2 - pregled uspjesno kreiranog materijala
![screenshot_6](https://cloud.githubusercontent.com/assets/11351969/7824722/823c7e14-0405-11e5-984d-ee23bd1621d2.png)

**Comment by luka454** [comment]
Poštovani kolega,

ovakvo ponašanje je validno i u skladu s SRSom. Naime ponuđene mjerne jedinice u comboboxu služe samo kao prijedlozi korisniku kako bi mu se omogućio lakši (i brži) rad s aplikacijom, a samog korisnika ne želimo ograničavati pri unosu mjerne jedinice. Pobrojati sve moguće mjerne jedinice ne bi bilo praktično

**Comment by FarukLjuca** [comment]
Kolega Luka,

Slažem se da ne bi bilo praktično pobrojavati sve mjerne jedinice, međutim bilo bi poželjno uvesti bar neku validaciju polja.
Slažem se i sa tim da je u skladu sa SRS-om, ali da li je mjerna jedinica bez ikakve validacije pametna ili kao što sam gore naveo - bilo šta.
Da li je vama prihvatljivo imati mjeru jedinicu koja se zove *?=)(/&%$#"!0987654321, kao sto sam je uspjesno i unjeo na slici ispod.
Ovo jeste u skladu sa SRS-om, al onda to samo znači da je greška i u SRS-u.

![screenshot_1](https://cloud.githubusercontent.com/assets/11351969/7843755/0d3bdc2a-04ac-11e5-9adb-64c2dad37189.png)

**Comment by SumejjaPorca** [comment]
Općepoznato je da za neke stvari nema smisla uvoditi validaciju -> kao npr. ime ili prezime... Pa tako i za mjernu jedinicu... Obzirom da ne može "nauditi" sistemu i da je samo stvar prikaza za klijenta, njegova je stvar sta želi unositi... A vodili smo se onim što klijent želi. :)
