### ISSUE TITLE
Zahtjev 'Pregled zauzetosti doktora' nije realiziran

### ISSUE THREAD

**Issue by AdnanLFC** [SoftverInzenjeringETFSA/SI2014Tim12#38]
Zahtjev 'Pregled zauzetosti doktora' naveden u dokumentu 'Specifikacija softverskih zahtjeva (SRS)' pod 'Upravljanje terminima za posjete' nije realiziran.

**Comment by SumejjaPorca** [comment]
Jeste :D Kod pretrage termina moze se ukucati naziv doktora i tako se moze vidjeti Koje termine u buducnosti on ima - kad je zauzet, pa je to pregled zauzetosti doktora. Po specifikaciji SRS-a, sve uslove ispunjava kao funkcionalnost.
