### ISSUE TITLE
Zakazivanje termina za vrijeme u prošlosti i sa neispravnim podacima

### ISSUE THREAD

**Issue by AnesaDrakovac** [SoftverInzenjeringETFSA/SI2014Tim12#41]
Komponenta:
RezervacijaTerminaGUI.java

Commit ID:
9e776b2

Opis problema:
Kada se vrši rezervacija termina za pacijenta, pri unosu je moguće unijeti nevalidne podatke za polja 'Doktor', 'Vrijeme' i 'Datum'.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju prema datom uputstvu unutar projekta;
2. Izvršiti prijavu;
3. Na glavnom izborniku izabrati opciju 'Termini', zatim izabrati opciju 'Novi pacijent' radi demonstracije;
4. Dodati novog pacijenta i zatvoriti formu 'Rezervacija termina' ;
5. Otvara se forma 'Zakazivanje termina';
6. U polju 'Pacijent' odaberemo nekog pacijenta: npr. Neko Nekic;
7. U polju 'Doktor' upišemo: npr. '111111';
8. Za polje 'Datum' odaberemo neki prošli datum: npr. 15.5.2015.

Dobijeni rezultat:
- Obavještenje da je termin uspješno registriran. http://prntscr.com/79sarw

Očekivani rezultat:
- Upozorenje o greški da polje 'Datum' ne može biti neki datum iz prošlog vremena, ili jednostavno zabraniti opciju odabira datuma prije trenutnog.
- Upozorenje o greški da polje 'Doktor' smije sadržavati samo slova, ne i brojeve i ostale znakove.

**Comment by SumejjaPorca** [comment]
Nevalidirano polje za vrijeme termina je već prijavljeno unutar issue-a #28. 
Neispravni podaci se odnose na nevalidaciju imena? Smatram da je validacija imena veoma nezahvalna, neko je to na stackoverflow lijepo rekao:
"I think your choice of RegEx to validate names is missing the point: this is a huge unwieldy problem and, even if you massively restrict the scope of names you allow, you will forever suffer the risk of false negatives and you will be turning away people from other cultures and languages. In other words, I don't think that even attempting to validate names is worth your time."(stackoverflow)

**Comment by EnilPajic** [comment]
Ovo je već prijavljeno, https://github.com/SoftverInzenjeringETFSA/SI2014Tim12/issues/28
I popravljeno prilikom popravljanja #28
