### ISSUE TITLE
Program krahira nakon promjene Vremenskog inrervala Od

### ISSUE THREAD

**Issue by FarukLjuca** [SoftverInzenjeringETFSA/SI2014Tim12#42]
Komponenta:
Forma - O svim ulazima

Commit ID:
9e776b20e3a1193cdb2122cd9637f3d014c0839d

Opis problema:
Program radi ok ukoliko se vremenski intervali ne pormjene (slika u Dodatne informacije). Međutim, kada se za vremenski interval Od postavi druga vrijednost (godina=2000 u primjeru (slika u Dodatne informacije)) program krahira i "baca" hilbernate.QueryException koji je uzrokovan InvalidArgumentException-om. Vidimo da je godina 2000 uredu, te je ovo greška.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "Zubarska ordinacija"
2. Logiranje
3. Izbor taba Izvještaji
4. Klik na dugme O svim ulazima
5. Klik na dugme Prikaži (dobijamo validne podatke (slika 1))
6. Promjena godine datima Od na 2000 (slika 2)

Dobijeni rezultat:
- GUI se ne mjenja, a program "baca" izuzetak

Očekivani rezultat:
- Adekvatno dobijanje izvještaja, u našem primjeru, praznog.

Dodaten informacije:
- Stack trace:
  http://pastebin.com/KVUepEN0

Slika 1 - korektan rad programa za godina = 1900
![screenshot_8](https://cloud.githubusercontent.com/assets/11351969/7825252/f7ad2144-040a-11e5-9588-4a390407b0c0.png)

Slika 2 - nekorektan rad programa za godina = 2000
![screenshot_9](https://cloud.githubusercontent.com/assets/11351969/7825260/07ee7e9a-040b-11e5-9f32-a95f9f700541.png)

**Comment by SumejjaPorca** [comment]
Duplikat od #33. Rijeseno.
