### ISSUE TITLE
Prikaz bosanskih slova Č, Ć i Đ kao upitnika

### ISSUE THREAD

**Issue by FarukLjuca** [SoftverInzenjeringETFSA/SI2014Tim12#43]
Komponenta:
Forma - Registracija posjeta / Prikaz posjeta

Commit ID:
9e776b20e3a1193cdb2122cd9637f3d014c0839d

Opis problema:
Bosanska slova Č, Ć i Đ se prikazuju kao upitnici, dok se slova Ž i Š ispravno prikazuju.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "Zubarska ordinacija"
2. Logiranje
3. Izbor taba Posjete
4. Klik na dugme Registracija posjeta
5. Popunjavanje svih parametara validno osim polja Doktor, gdje upisujemo Š Č Ć Ž Đ kao naziv doktora (može i npr. Kunić, što je validno ime doktora)
6. Klik na dugme Registruj posjetu
7. Klik na dugme prikaz posjeta
8. Klik na dugme pretraži (kako bismo dobili sve posjete ili prethodno ukucavanje dijagnoze postojeće posjete)

Dobijeni rezultat:
- Prikaz naziva doktora kao Š ? ? Ž ? (Kuni?)

Očekivani rezultat:
- Očekuje se korektan prikaz naziva doktora tj. Š Č Ć Ž Đ (Kunić)

Dodatje informacije:
Slika 1 - Unos nove posjete i popunjavanje polja Doktor
![screenshot_11](https://cloud.githubusercontent.com/assets/11351969/7825388/c2aa9092-040c-11e5-84aa-9d5368d233c7.png)

Slika 2 - Prikaz posjeta sa nevalidnim prikazom imena doktora
![screenshot_10](https://cloud.githubusercontent.com/assets/11351969/7825412/ed9fc1c8-040c-11e5-8aaa-f0696704d17c.png)

**Comment by luka454** [comment]
Ispravljeno.

Postavljen je novi init.sql: https://github.com/SoftverInzenjeringETFSA/SI2014Tim12/blob/master/Radni%20materijali/init.sql
