### ISSUE TITLE
Greška kod pregleda termina

### ISSUE THREAD

**Issue by AnesaDrakovac** [SoftverInzenjeringETFSA/SI2014Tim12#44]
Komponenta:
PrikazTerminaGUI.java

Commit ID:
b2b3aa3

Opis problema:
Na formi se ne prikazuju termini u tabelarnom prikazu. Dugme 'Pretraži' nema ulogu prikaza termina jer se pritiskom na njega za ispravno unesene vrijednosti pojavi sljedeće obavještenje: 'Pacijent sa id-om: 0 nije pronadjen.'.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju prema datom uputstvu unutar projekta;
2. Izvršiti prijavu;
3. Na glavnom izborniku izabrati opciju 'Termini', zatim izabrati opciju 'Pregled termina'.
4. Popunimo polja 'Termini od datuma' i 'Termini do datuma' sa npr. '1-1-2000' i '27-05-2015'.
5. U polje 'Doktor' unijeti npr. 'Doktor', (kod mene u bazi sam već unijela podatke za termin pacijenta kod doktora 'Doktor' da bih mogla testirati, na datoj slici ispod se vidi dio iz baze podataka za tabelu 'termini', a pregled unesenog pacijenta http://prntscr.com/79xh86);
5.1. Drugi slučaj je ako unesem ID broj pacijenta ili doktora, koji već postoje u bazi.
6. Kliknuti na dugme 'Pretraži';

Dobijeni rezultat:
- Neko obavještenje http://prntscr.com/79xjrq (pacijent sa id-om: 0 nije pronađen).
- Za drugi slučaj nema obavještenja ali opet ne izlistava termine.

Očekivani rezultat:
- Prikaz termina za unesenog doktora i termin. Ili ako ima neka greška, prikaz upozorenja o nemogućnosti prikaza termina za unesenog doktora (ili obavještenje o tome šta je potrebno unijeti za polje 'Doktor').

**Comment by EnilPajic** [comment]
- Ne može se 'svašta' unijeti u navedena polja, datum se sigurno _dobro_ validira. Šta fali unesenim datumima za koje navodite da se mogu unijeti "glupe vrijednosti"? Pretraga radi na principu da izlista termine unutar navedenog intervala.
  - Ako je interval veći od od nekog nekog razumnog (npr. stavimo da izlistava od 1990. do 2050.) to će svakako obuhvatiti sve termine, što i jeste cilj pretrage, a omogućava i univerzalnost.  
  - Ako je interval 'premal' da ne hvata termine, neće biti izlistano ništa. Međutim, **_postoji_** provjera  ako je uneseni datum 'od' veći (tj. kasniji) od datuma 'do' i da se ispiše greška.
- Dalje, u polje doktor je smisleno unijeti bilo šta, ako se ne poklapa _'pattern'_ pretrage sa rezultatima termina, neće biti izlistani termini. Uostalom, tako radi _svaki_ pretraživač, za neke unose ima rezultata a za neke nema. Ime doktora je samo string. Ako ja unesem '7' kao kriterij pretrage, i ako nema niti jedan doktor sa brojem '7' u imenu, neće biti izlistani termini, što je OK.

###### Stoga, očekivani rezultat o upozorenju o nevalidnim datumima (!?) nije opravdan.

Druga je priča što javlja grešku da ne postoji pacijent sa ID-om 0 (i zbog toga _prekine_ izlistavanje ostalih pacijenata), tu ste u pravu, greška je već napomenuta (samo napomenuta) u #27. Hvala na prijavi **bug**-a!

**Comment by SumejjaPorca** [comment]
Ispravljeno..
