### ISSUE TITLE
Nisu validirana polja za unos podataka o pacijentu

### ISSUE THREAD

**Issue by sgrosic1** [SoftverInzenjeringETFSA/SI2014Tim12#45]
Komponenta:
Registracija novog pacijenta 

commit ID:
9e776b20e3a1193cdb2122cd9637f3d014c0839d

Opis problema:
Polja "Ime i prezime" i "Broj telefona", nisu validirana. U ta polja se mogu unositi karakteri bilo kojeg tipa, što ne bi trebalo biti omogućeno.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "Zubarska ordinacija (by LunaSoft) prema uputstvu na linku 
(https://github.com/SoftverInzenjeringETFSA/SI2014Tim12/blob/master/Documents/UputstvoZaRazvojnoOkruzenje.pdf).
2. Izabrati opciju "Pacijenti" na glavnom meniju.
3. Zatim izabrati opciju "Kreiraj novog pacijenta"
4. U polje "Ime i prezime" unijeti "sabina7".
5. U polje "Broj telefona" unijeti "&76(9"
6. U polje "Datum rođenja" unijeti "11-05-1992"
7. U polje "Opis" unijeti "Opis Opis"
8. Kliknuti dugme "Kreiraj"

Dobijeni rezultat:
- Pacijent se uspješno kreira (http://prntscr.com/79y214) i spremi u bazu (http://prntscr.com/79y47i).

Očekivani rezultat:
- Očekuje se da  bude spriječen unos i spremanje u bazu besmislenih podataka u poljima "Ime i prezime" i "Broj telefona".

**Comment by luka454** [comment]
Dupliciran #36
