### ISSUE TITLE
Materijal kod kreiranja novog tipa zahvata se ne sprema u bazu

### ISSUE THREAD

**Issue by AnesaDrakovac** [SoftverInzenjeringETFSA/SI2014Tim12#46]
Komponenta:
KreiranjeZahvataGUI.java

Commit ID:
01890a7

Opis problema:
Pri kreiranju novog zahvata, odabere se materijal za taj zahvat i dobije se obavještenje da je novi zahvat uspješno kreiran. Međutim u bazi u tabeli 'materijaltipzahvata' se ne registruje materijal za taj tip zahvata.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju prema datom uputstvu unutar projekta;
2. Izvršiti prijavu;
3. Na glavnom izborniku izabrati opciju 'Materijali', zatim izabrati opciju 'Dodavanje materijala';
4. Dodati novi materijal i zatvoriti formu 'Dodavanje novog materijala', http://prntscr.com/79yupg;
5. Na glavnom izborniku izabrati opciju 'Zahvati', zatim izabrati opciju 'Dodavanje zahvata';
6. Odabrati prethodno kreirani materijal i kreirati novi zahvat sa traženim podacima, http://prntscr.com/79yw9k.

Dobijeni rezultat:
- Kreira se novi tip zahvata sa odabranim materijalom, ali se to ne registruje u bazi podataka. http://prntscr.com/79yyo4

Očekivani rezultat:
- Nakon unosa novog tipa zahvata, u bazi treba takođe da se kreira materijal sa tim tipom zahvata u tabeli 'materijaltipzahvata'.

**Comment by luka454** [comment]
Ispravljeno.

commit ID:
55bcc1926010134def68f8d2e99903844fbd140a
