### ISSUE TITLE
Zakazivanje termina - polje "Vrijeme" i polje "Doktor" nije validirano

### ISSUE THREAD

**Issue by sgrosic1** [SoftverInzenjeringETFSA/SI2014Tim12#47]
Komponenta:
Zakazivanje termina

commit ID:
9e776b2

Opis problema:
Polje "Vrijeme" i polje "Doktor" nije validirano.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "Zubarska ordinacija (by LunaSoft) prema uputstvu na linku 
(https://github.com/SoftverInzenjeringETFSA/SI2014Tim12/blob/master/Documents/UputstvoZaRazvojnoOkruzenje.pdf).
2. Izabrati opciju "Termini" na glavnom meniju.
3. Zatim izabrati opciju "Zakazivanje termina"
4. Odabrati pacijenta u combobox-u Pacijent.
5. U polje "Doktor unijeti "Doktor Doktorović"
6. U polje "Vrijeme" unijeti "11:62"
7. Kliknuti dugme "Registruj novi termin"

Dobijeni rezultat:

Termin se uspješno kreira (http://prntscr.com/7a096e) i spremi u bazu (http://prntscr.com/7a09jr).

Očekivani rezultat:
Očekuje se da bude spriječen unos i spremanje u bazu besmislenih podataka vezanih za termin.

**Comment by SumejjaPorca** [comment]
Nevalidirano polje za vrijeme termina je već prijavljeno unutar issue-a #28. U polje Doktor se može unijeti bilo koje ime i prezime za doktora, tako je u intervjuu naglašeno, kao i u SRS-u. To je obični string i to je ok. Jeste li na to mislili?
