### ISSUE TITLE
Dodavanje materijala - polje Naziv nije validirano

### ISSUE THREAD

**Issue by sgrosic1** [SoftverInzenjeringETFSA/SI2014Tim12#48]
Komponenta:
Dodavanje novog materijala

commit ID:
9e776b2

Opis problema:
Polje "Naziv"  nije validirano.

Koraci za reproduciranje problema:
1. Pokrenuti desktop aplikaciju "Zubarska ordinacija (by LunaSoft) prema uputstvu na linku 
(https://github.com/SoftverInzenjeringETFSA/SI2014Tim12/blob/master/Documents/UputstvoZaRazvojnoOkruzenje.pdf).
2. Izabrati opciju "Materijali" na glavnom meniju.
3. Zatim izabrati opciju "Dodavanje novog materijala"
4. U polje "Naziv" unijeti "22222"
7. Kliknuti dugme "Kreiraj"

Dobijeni rezultat:
Materijal se uspješno kreira (http://prntscr.com/7a0bkz) i spremi u bazu.

Očekivani rezultat:
Polje "Naziv" bi trebalo biti validirano, da bude onemogućen unos brojeva kao naziv materijala koji će biti spremljen u bazu.

**Comment by luka454** [comment]
Kolegice,

evo dva realna primjera stomatoloških materijala:
http://nowakdental.com/cgi-bin/nwd/rtl/prd_d.cgi?category=Disposables
http://nowakdental.com/cgi-bin/nwd/rtl/prd_d.cgi?category=Brushes%20and%20Buffs+Buffs

Kao što vidite brojevi se i više nego koriste u nazivima materijala. Također pored brojeva se koriste i drugi znakovi #('.-/
Gdje napraviti granicu?
