### ISSUE TITLE
Kreiranje novog zahvata prolazi bez validacije praznih polja i zahvat se ne može naknadno mijenjati

### ISSUE THREAD

**Issue by AnesaDrakovac** [SoftverInzenjeringETFSA/SI2014Tim12#50]
Komponenta:
KreiranjeZahvataGUI.java

Commit ID:
01890a7

Opis problema:
Kada se kreira novi zahvat, a ne unesu se samo polja: 'Naziv' i 'Cijena', dobija se obavještenje da je zahvat uspješno kreiran, iako sljedeća polja nisu ispunjena: 'Materijal', 'Količina'. Nigdje nije omogućeno da se informacije o zahvatu mogu naknadno mijenjati.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju prema datom uputstvu unutar projekta;
2. Izvršiti prijavu;
3. Na glavnom izborniku izabrati opciju 'Zahvati', zatim izabrati opciju 'Dodavanje zahvata';
4. Dodati novi zahvat, unošenjem samo polja 'Naziv', npr. 'ZahvatZaGresku' i polje 'Cijena', npr. 5 'Rezervacija termina'; 
5. Kliknuti na dugme 'Kreiraj zah...', http://prntscr.com/7a0evb;
6. Zatvoriti formu 'Kreiranje zahvata';

Dobijeni rezultat:
- Novi zahvat se kreira sa ovakvim podacima iako ima praznih polja za taj zahvat. Naknadno nigdje ne postoji mogućnost da se podaci o tom zahvatu mijenjaju, npr. da se doda materijal i količina materijala za taj zahvat, http://prntscr.com/7a0fbb.

Očekivani rezultat:
- Upozorenje o greški da se nepopunjena polja trebaju popuniti ili da se mogu izmijeniti u pregledu tog zahvata naknadno.

**Comment by luka454** [comment]
Kolegice,

Čini mi se geškom da ste ponovili: https://github.com/SoftverInzenjeringETFSA/SI2014Tim12/issues/51
Ili čini mi se da ste tamo greškom ponovili dio ovog.

Sada mi je malo razumljivije što ste željeli reći međuđitim još uvijek mi nisu jasna dvije stvari od ranije:
- Da li ste u opisu slučajno mislili 'a unesu se samo polja: Naziv i Cijena', umjesto 'a NE unesu se samo polja: Naziv i Cijena'
- Što vam znači 'Rezervacija termina' u koracijama za reprodukciju korak četvrti?

Te još jedna stvar, koja je napomenuta u Projektnom zadatku 10 koja su to koja očekujete da moraju biti popunjen?

Također ukoliko opet pretpostavim iste stvari vrijedi sljedeće (pročitajte i gore linkovani issue #51 ) i ukoliko pretpostavim da ste mislili na sva polja da moraju biti popunjena važi sljedeće:
- Moguće je da postoji zahvat bez materijala za koje se pretpostavlja da će se potrošiti (detaljno objašnjeno u issue #51 ).
- Ukoliko ste pročitali SRS mogli ste vidjeti da polje Opis nije zahtijevano polje tako da može biti prazno
- Ukoliko pogledate SRS ne postoji funkcionalnost promjene zahvata, osim njegove cijene. SRS je rađen prema interview-u i ponudi. Ispoštovani su zahtjevi kupca, a dodatne funkcionalnosti nisu dodavane, jer bi to značilo i veću cijenu softvera što nije u intereseu kupca

Ukoliko je došlo do nesporazuma, molim Vas da mi javite u što kraćemo roku kako bi uklonili isti.
Srdačan pozdrav,
Luka

**Comment by AnesaDrakovac** [comment]
Pozdrav,

Zbog moje greške je issue #51 ispravljen. A prema vašem odgovoru, onda ovaj issue ostaje sa stanjem 'NotValid'.
Hvala.

Lp.
