### ISSUE TITLE
Ne vidi se naziv ponuđene opcije na formi

### ISSUE THREAD

**Issue by AnesaDrakovac** [SoftverInzenjeringETFSA/SI2014Tim12#51]
Komponenta:
KreiranjeZahvataGUI.java

Commit ID:
01890a7

Opis problema:
Kada popunimo podatke za kreiranje zahvata, ne vidi se puni naziv dugmeta na koje možemo kliknuti.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju prema datom uputstvu unutar projekta;
2. Izvršiti prijavu;
3. Na glavnom izborniku izabrati opciju 'Zahvati', zatim izabrati opciju 'Dodavanje zahvata', http://prntscr.com/7asif0;

Dobijeni rezultat:
- Može se kliknuti na opciju 'Kreiranje zah...', ali se može desiti da korisnik ne zna šta ona predstavlja.

Očekivani rezultat:
- Treba da se vidi cijeli naziv opcije da se korisnik ne bi zbunio.

**Comment by luka454** [comment]
Zdravo kolegice,

Izvinjavam se ako je do mene, ali opis ovog Buga mi je malo konfuzan.
- Da li ste u opisu slučajno mislili  'a unesu se samo polja: Naziv i Cijena', umjesto 'a NE unesu se samo polja: Naziv i Cijena'
- Što vam znači 'Rezervacija termina' u koracijama za reprodukciju korak četvrti?
- Dobiveni rezultati me također zbunjuju, ne mogu zaključiti kakve veze imaju sa materijalima i njihovom količinom. Također, ne znam kakav ste rezultat očekivali što se tiče neunesenih materijala i količina.

Molim Vas da nam odgovorite kako ne bi došlo do zabune.

Također, slažem se da je dugme 'Kreiranje zah...' zbunjujuće te ći isto biti prepravljeno na 'Kreiraj' u sljedećem commitu
Također, ukoliko ste mislili da se zahvat može dodati bez materijala i količine, to je validno ponašanje jer za neke zahvate materijali se ne troše ili je njihova potrošnja irelevantna, npr. pregled pacijenta nakon koje je potrebno samo očistiti stomatološke instrumente, a pri tome je moguće da se ne potroši ništa materijala. 

Još jednom bih Vas zamolio da nam odgovorite kako ne bi došlo do neke zabune.

Srdačan podrav,
Luka

**Comment by AnesaDrakovac** [comment]
Pozdrav,

Oprostite na pogreški. Ispravila sam komentar. Naglasak ovog issue-a je na opciji koja se u potpunosti ne vidi. Stari komentar se može ovdje vidjeti: http://prntscr.com/7ash97.
Hvala.

Lp.

**Comment by luka454** [comment]
Ispravljeno

commit ID 3e2973b49b7b61a65644af5b539b0fae5cf3c124
