### ISSUE TITLE
UIS - slijed rada sa pacijentima i polja kod prikaza info o pacijentu nisu u skladu sa aplikacijom

### ISSUE THREAD

**Issue by AnesaDrakovac** [SoftverInzenjeringETFSA/SI2014Tim12#54]
Komponenta:
PacijentiGUI.java

Commit ID:
f1ccd7f

Opis problema:
Zadnja verzija dokumenta 'UIS v1.2.pdf' se ne slaže sa izgledom i radom sa formom za prikaz informacija o pacijentu. U dokumentu piše sljedeće: 'Odabirom pacijenta na ekranu za manipulaciju pacijenata otvara se detaljan prikaz pacijenta' (http://prntscr.com/7a2jnx), a u aplikaciji se to vrši u opisu koraka za reproduciranje problema (http://prntscr.com/7a2lpp).

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju prema datom uputstvu unutar projekta;
2. Izvršiti prijavu;
3. Na glavnom izborniku izabrati opciju 'Pacijenti', zatim izabrati opciju 'Prikaz pacijenta';
4. Odabrati pretraživanje po 'Imenu i prezimenu' i za tu opciju ostaviti prazan unos.
5. Kliknuti na dugme 'Pretraži';
6. Unutar tabele izlistanih pacijenata, odabrati nekog pacijenta;
7. Na glavnom izborniku forme izabrati opciju 'Informacije o pacijentu'.

**Comment by luka454** [comment]
Kolegice,

Ovde bih se odmah pozvao na sljedeću stavku iz projektnog zadatka 10 u kome piše da će se priznavati bugovi koji:
- nisu besmisleni, nepopravljivi ili očigledna posljedica odabrane arhitekture aplikacije, dizajna, korištenih tehnologija itd.

Kako je jedina razlika dokumenta i realiziranog ta što je u dokumentu navedeno da se odabirom pacijenta otvara, a ovamo je potrebno nakon odabira pacijenta i pritisnuti dugme, smatram ovo invalidnim, jer je to posljedica odabranih tehnologija.

Naime za prikaz pacijenata korišten JTable koji ne posjetuje DoubleClick event za odabir nekog reda(pacijenta), stoga smatram da je dodavanje dugmeta na koje bi se otvorio prikazani pacijent i u najboljem interesu samog korisnika (kupca).
