### ISSUE TITLE
UIS - rad sa terminima u aplikaciji nije u skladu sa opisanim akcijama u specifikaciji korisničkog interfejsa

### ISSUE THREAD

**Issue by AnesaDrakovac** [SoftverInzenjeringETFSA/SI2014Tim12#55]
Komponenta:
PrikazTerminaGUI.java

Commit ID:
b2b3aa3

Opis problema:
Zadnja verzija dokumenta 'UIS v1.2.pdf' se ne slaže sa izgledom i radom sa formom za pregled termina. U dokumentu piše sljedeće: 'Ova forma sadrži kalendar. Klikom na određeni datum prikazuju se zakazani termini za taj datum. Izgled kalendara se može mijenjati između sedmičnog i mjesečnog.'. Tu je omogućeno samo registrovanje novog termina dok se u aplikaciji može dodati posjeta i otkazati termin, a pregled termina se vrši u određenom vremenskom periodu po doktoru. (http://prntscr.com/7a2wwl)

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju prema datom uputstvu unutar projekta;
2. Izvršiti prijavu;
3. Na glavnom izborniku izabrati opciju 'Termini', zatim izabrati opciju 'Pregled termina'.
4. Na formi 'Termini', termini se mogu prikazati za određeni period i odabranog doktora.

**Comment by SumejjaPorca** [comment]
Posjeta i termin nemaju veze, moze se otkazivati termin bez obzira na posjetu. 
Moguce je pregledati i mjesecne i sedmicne termine, bez ukucavanja doktora, jedino sto fali je kalendar razlicit za sedmicu i razlicit za mjesece.

**Comment by SumejjaPorca** [comment]
Ajde dodat ćemo taj kalendar. :)
