### ISSUE TITLE
Tabela za prikaz pacijenata

### ISSUE THREAD

**Issue by AnesaDrakovac** [SoftverInzenjeringETFSA/SI2014Tim12#56]
Komponenta:
PacijentiGUI.java

Commit ID:
f1ccd7f

Opis problema:
Kada se otvori tabela sa prikazom pacijenata, kolona za 'Opis' nije dovoljno velika da mogu stati svi podaci iz opisa tako da se vide.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju prema datom uputstvu unutar projekta;
2. Izvršiti prijavu;
3. Na glavnom izborniku izabrati opciju 'Pacijenti', zatim izabrati opciju 'Prikaz pacijenta';
4. Nakon toga u pretrazi odabrati kriterij pretrage po 'Imenu i prezimenu' i u polje za unos ne unositi ništa;
5. Kliknuti na dugme 'Pretraži';
6. U tabeli se prikažu svi pacijenti.

Dobijeni rezultat:
- U tabeli pacijenata za prikaz informacija o pacijentima, polje za 'Opis' u tabeli nije dovoljno veliko da bi se vidio cijeli opis ukoliko je duži. http://prntscr.com/7a5cme

Očekivani rezultat:
- Treba da se vidi cijelo polje 'Opis' u tabeli za prikaz pacijenata..

**Comment by luka454** [comment]
Kolegice, 

Polje Opis sadrži 255 znakova, što je otprilike puna tri ispisana reda ovdje na githubu, te bi prikazati cijeli opis u tabeli bilo nepraktično. Zbog toga postoji opcija prikaži pacijenta(informacije o pacijentu) u kojoj možete vidjet cijeli opis.

Ako Vi imate bolji prijedlog javite.

Srdačan pozdrav,
Luka

**Comment by luka454** [comment]
Kolegice,

Kada sam još jednom pročitao projektni zadatak 10 iz predmeta Softver inžinjering, pročitao sam da neće biti priznavani bugovi koji su očigledna posljedica odabrane tehnologije i dizajna.
Stoga, smatram da ovaj bug nije validan jer prikazati 255 karaktera u jednoj koloni jednog reda komponente JTable i nije baš moguće.

Ukoliko Vi smatrate drukčije javite.

Srdačan pozdrav,
Luka

**Comment by AnesaDrakovac** [comment]
Pozdrav,

Vaš odgovor je opravdan.
Hvala.

Lp.
