### ISSUE TITLE
Forma nema title

### ISSUE THREAD

**Issue by AnesaDrakovac** [SoftverInzenjeringETFSA/SI2014Tim12#57]
Komponenta:
PacijentiGUI.java

Commit ID:
f1ccd7f

Opis problema:
Kada se klikne na opciju 'Pacijenti' na glavnom izborniku, a zatim na opciju 'Prikaz pacijenta' otvori se forma koja nema naslov. (Mislim da je to jedina forma bez naslova). Inače, u UIS-u naslov ove forme je 'Pacijenti'. Pa samo bi trebalo postaviti title. http://prntscr.com/7a5hfa

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju prema datom uputstvu unutar projekta;
2. Izvršiti prijavu;
3. Na glavnom izborniku izabrati opciju 'Pacijenti';
4. Kliknuti na opciju 'Prikaz pacijenta';
4. Otvori se nova forma;

Dobijeni rezultat:
- Otvara se forma bez naslova. To može zbuniti korisnika.

Očekivani rezultat:
- Otvorena forma treba imati naslov zbog korisnikove navigacije i lakšeg snalaženja.

**Comment by luka454** [comment]
Ispravljeno.

Commit id
55bcc1926010134def68f8d2e99903844fbd140a
