### ISSUE TITLE
UIS - neusaglašenost forme za prijavu korisnika

### ISSUE THREAD

**Issue by AnesaDrakovac** [SoftverInzenjeringETFSA/SI2014Tim12#58]
Komponenta:
LoginGUI.java

Commit ID:
0d039ef

Opis problema:
Kada se pokrene aplikacija, pored opcije za prijavu se nudi i opcija 'Zatvori' koja prema specifikaciji korisničkog interfejsa nije specificirana.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju prema datom uputstvu unutar projekta;

Dobijeni rezultat:
- Otvara se forma za prijavu korisnika sa opcijom 'Zatvori': http://prntscr.com/7at39s

Očekivani rezultat:
- Otvorena forma za prijavu korisnika prema posljednjoj verziji specifikacije korisničkog interfejsa (UIS v1.2) treba da ima samo opciju 'Prijavi se', ne i 'Zatvori': http://prntscr.com/7at08f.

**Comment by luka454** [comment]
Neusaglašeno je bilo zbog tehničkih problema.
Ali riješili smo ih
