### ISSUE TITLE
Ime i prezime nije validirano prilikom unosa pacijenta

### ISSUE THREAD

**Issue by tms1337** [SoftverInzenjeringETFSA/SI2014Tim12#60]
Komponenta:
Megadigitron desktop

commit ID:
7b9190b14862b26bed69bc1ac66c64957868ff6d

Opis problema:
Nije validirano polje Ime i prezime prilikom unosa pacijenta

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju uz unos tacnih login podatke
2. Unutar taba pacijenti pokrenuti kreiranje novog pacijenta pritiskom na odgovarajuci button
3. U polje 'Ime i prezime' unijeti '<....>...' ili neki slican random niz znakova koji zasigurno ne predstavlja ime i prezime
4. Popuniti validno ostale podatke
5. Pritisnuti button dodaj

Dobijeni rezultat:
- Ispisuje se messagebox sa textom 'Pacijent je uspjesno dodan', te se pacijent zaista dodaje u sistem sto se moze provjeriti pritiskom na dugme 'Prikaz pacijenata' u tabu Pacijenti

Očekivani rezultat:
- Ocekuje se da se prijavi validaciona greska na neki nacin i korisniku se da do znanja da uneseni podaci nisu validni, te se ne bi smjelo desiti da se ovako misformed pacijent unes u sistem.

**Comment by tms1337** [comment]
komponenta nije magadigitron nego KreiranjePacijentaGUI.java haha

**Comment by luka454** [comment]
Duplikat #36
