### ISSUE TITLE
Datum rodjenja propusta nedozvoljene ulaze (Dodavanje pacijenta)

### ISSUE THREAD

**Issue by tms1337** [SoftverInzenjeringETFSA/SI2014Tim12#61]
Komponenta:
KreiranjePacijentaGUI.java

commit ID:
7b9190b14862b26bed69bc1ac66c64957868ff6d

Opis problema:
Polje datum rodjenja prilikom kreiranja pacijenta nije validirano te propusta da se unesu nedozvoljene vrijednosti, iako se u bazu upisuje pravilan datum, tako da se ovo vise odnosi na intuitivnost user interface-a nego na samu funkcionalnost.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju uz unos tacnih login podatke
2. Unutar taba pacijenti pokrenuti kreiranje novog pacijenta pritiskom na odgovarajuci button
3. Tacno popuniti polja koja nisu datum rodjenja (validnim podacima)
4. U polje datum unijeti '21-08-1994asadasd'
5. Pritisnuti button 'Dodaj pacijenta'

Dobijeni rezultat:

http://imgur.com/5Fv5brD
Ispisuje se messagebox sa textom 'Pacijent je uspjesno dodan', te se pacijent zaista dodaje u sistem sto se moze provjeriti pritiskom na dugme 'Prikaz pacijenata' u tabu Pacijenti

Očekivani rezultat:

Ocekuje se da se prijavi validaciona greska na neki nacin i korisniku se da do znanja da uneseni podaci nisu validni, te se ne bi smjelo desiti da se ovako misformed pacijent unes u sistem. U ovom slucaju korisnik se validno unese u sistem, ali je omogucen unos nedozvoljenog ulaza.

**Comment by tms1337** [comment]
moguce je unijeti i datum > od danasnjeg

**Comment by luka454** [comment]
Slično #36 , međutim tamo nema opisan error pri dodavanju slova na kraju datuma i da je datum veći od današnjeg
