### ISSUE TITLE
Promjene nisu odmah registrovane u tabeli - modifikacija pacijenta

### ISSUE THREAD

**Issue by tms1337** [SoftverInzenjeringETFSA/SI2014Tim12#65]
Komponenta:
ModifikacijaPacijentaGUI.java

commit ID:
7b9190b14862b26bed69bc1ac66c64957868ff6d

Opis problema:
Promjene u pacijentu se ne registruju u tabeli za prikaz pacijenata.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju uz unos tacnih login podatke
2. Unutar taba pacijenti pristupiti prikazu pacijenata pritiskom na odgovarajuci button
3. Izabrati jednog od postojecih pacijenata za modifikaciju (prethodno unijeti pacijenta if necessary)
4. Modifikovati neke od podataka u formi
5. Potvrditi modifikaciju i napustiti formu za modifikaciju 

Dobijeni rezultat:

Prikaz pacijenata u predvidjenoj tabeli koja se prikaze nakon sto se zatvori forma za modifikaciju ne registruje unese promjene dok se tabela ne refresha ili se nanovo unese neki od parametera za pretragu.

Očekivani rezultat:

Tabela bi trebala da se update, jer sada postoji mogucnost da korisnik pogresno pomisli da podaci nisu onakvi kakvi trebaju biti i ponovo ih modifikuje, dok su u tabeli zapravo stari podaci

**Comment by tms1337** [comment]
Komponenta += PrikazPacijentaGUI.java

**Comment by luka454** [comment]
Može se modificirati komentar

**Comment by tms1337** [comment]
ma znam neg nek vide ljudi da sam pogrijesio. treba da patim zbog togaa
