### ISSUE TITLE
Greska prilikom ponovnog otvaranja informacija o pacijentu

### ISSUE THREAD

**Issue by tms1337** [SoftverInzenjeringETFSA/SI2014Tim12#66]
Komponenta:
PrikazPacijentaGUI.java
informacije o pacijentu

commit ID:
7b9190b14862b26bed69bc1ac66c64957868ff6d

Opis problema:
Ne moze se 2 puta zaredom otvoriti informacija o pacijentu (>2)

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju uz unos tacnih login podatke
2. Unutar taba pacijenti pristupiti prikazu pacijenata pritiskom na odgovarajuci button
3. Izabrati jednog od postojecih pacijenata za modifikaciju (prethodno unijeti pacijenta if necessary)
4. Izabrati opciju za prikaz informacija o pacijentu
5. Izadji iz informacija
6. Ponovo pritisnuti prikaz informacija bez promjene selekcije

Dobijeni rezultat:

Nista se ne desi.

Očekivani rezultat:

Trebalo bi da se ipak otvori frame za pregled informacija o pacijentu.

**Comment by luka454** [comment]
Duplicirano #26
