### ISSUE TITLE
Moguce kucati custom tekst u selekciju pacijenta - nemoguce submitat formu (kreiranje posjete)

### ISSUE THREAD

**Issue by tms1337** [SoftverInzenjeringETFSA/SI2014Tim12#67]
Komponenta:
Posjete.java
PosjeteGUI.java

commit ID:
7b9190b14862b26bed69bc1ac66c64957868ff6d

Opis problema:
Moguc je niz koraka koji onemgucava submitanje forme, te zahtjeva izlaz iz iste

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju uz unos tacnih login podatke
2. Unutar taba posjete izabrati 'Registracija posjete'
3. Izabrati nekog od postojecih pacijenata u dropdownu
4. Dodati na izabranog pacijenta tekst 'aaa' klikom na tekstualni dio dropdowna
5. Popuniti validno ostale podatk
6. Pokusati submitati formu (frame)

Dobijeni rezultat:

http://imgur.com/CCB6Z5o
Nije moguce izvrstiti submit forme, jer sta god uradili podaci nece vise biti validni, a i dropdown je izgubio svoje opcije editovanjem.

Očekivani rezultat:

Nemogucnost editovanja dropdown texta.

**Comment by luka454** [comment]
Kolega,

U combobox smo pored klasične njegove funkcionalnosti da prikažemo sve korisnike i da jednog od njih naskrolamo i odaberemo (koju smatramo nepraktičnom, jer u bazi se mogu nalaziti tisuće korisnika) dodali i funkcionalnost (na koju smo JAKO ponosni) da u combobox možete ukucavati ime pacijenta kojeg želite. Kako ukucavate ime svog pacijenta, sistem vam u combobox ispod smiješta pacijente koji odgovaraju po imenu. Pacijenta možete odabrati iz ponuđenih i savršeno će raditi. Međutim, ako ukucate 'aaa' ili samo 'a' zatražili ste od sistema da vam pronađe pacijenta koji sigurno ne postoji.

Štoviše, ponašanje koje ste naveli smatramo greškom jer pacijent kome dodate neka slova više nije taj pacijent.

Srdačan pozdrav,
Luka
