### ISSUE TITLE
Nije validirana kolicina materijala - dodavanje zahvata

### ISSUE THREAD

**Issue by tms1337** [SoftverInzenjeringETFSA/SI2014Tim12#68]
Komponenta:
KreiranjeZahvataGUI.java

commit ID:
7b9190b14862b26bed69bc1ac66c64957868ff6d

Opis problema:
Nije validirana kolicina materijala koji se dodaje u zahvat, te to onemogucava submit forme za dodavanje materijala i primorava korisnika na iskljucivanje/ukljucivanje iste.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju uz unos tacnih login podatke
2. Unutar taba zahvati pokrenuti dodavanje novog zahvata
3. Izabrati materijal i unijeti neku od sljedecih kolicina:
'' - empty string
'asd'
'123.123,123.123'
4. Validno unijeti ostale podatke
5. Pokusati submitat formu

Dobijeni rezultat:

http://imgur.com/cbsPaTZ
Nije moguce submit formu, niti je na bilo koji nacin osim ponovnog pokretanja forme moguce ispraviti nevalidnost podataka. 

Očekivani rezultat:

Nemogucnost unosa divljih vrijednosti kolicine materijala u koraku 3, te mogucnost submitanja forme consequently.

**Comment by EnilPajic** [comment]
Popravljeno, _commit ID:_ 066ed8de054821b04e4eb45f295235e557bd88f8

**Comment by luka454** [comment]
Također bih napomenuo da se količina materijala može naknadno izmijeniti u tabeli. Tako ukoliko nije unesena cijena iznad može se naknadno u tabeli unijeti
