### ISSUE TITLE
Nemoguće je kreirati zahvat ukoliko se pogrješi količina

### ISSUE THREAD

**Issue by denisdzafo** [SoftverInzenjeringETFSA/SI2014Tim12#69]
Komponenta:
Kreiranje zahvata

Opis problema:
Ukoliko korisnik ne unese prvi put količinu materijala, i nakon prijavljene poruke da nije unio količinu materijala, nemoguće je kreirati  materijal ukoliko naknadno unese količinu.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju prema datom uputstvu unutar projekta;
2. Izvršiti prijavu;
3. Na glavnom izborniku izabrati opciju 'Kreiranje zahvata', zatim unese sve unose osim količine.
4. Kliknuti na dugme 'Unesite decimalni broj za količinu materijala'
5. Unjeti sve podatke.
6. Kliknuti na dugme 'Kreiraj

Dobijeni rezultat:
Poruka sa tekstom 'Unesite decimalni broj za količinu materijala' http://i.imgur.com/72SUW5E.jpg

Očekivani rezultat:
Poruka o usješnosti kreiranja zahvata.

**Comment by luka454** [comment]
Poštovani kolega,

Nakon dodavanja materijala, njihovu količinu je moguće uređivati u tabeli dvoklikom na željenu ćeliju. Pa samim tim ukoliko niste odmah unijeli količinu materijala možete je naknadno u tabeli dodati.
