### ISSUE TITLE
Moguće kreirati zahvat bez unosa materijala

### ISSUE THREAD

**Issue by denisdzafo** [SoftverInzenjeringETFSA/SI2014Tim12#70]
Komponenta:
Kreiranje zahvata

Opis problema:
Ukoliko korisnik ne unese podatke o materijalu, moguće je kerirati zahvat.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju prema datom uputstvu unutar projekta;
2. Izvršiti prijavu;
3. Na glavnom izborniku izabrati opciju 'Kreiranje zahvata', zatim unesu svi podaci osim podataka o materijalu.
4. Kliknuti na dugme 'Kreiraj

Dobijeni rezultat:
Poruka sa tekstom 'Uspješno kreiran zahvat' http://i.imgur.com/rPsyhym.jpg

Očekivani rezultat:
Obavijest da materijal nije unesen.

**Comment by luka454** [comment]
Duplicirano #50 

Objašnjenje možete pogledati na referenciranom postu, ukoliko nešto ostane nejasno recite :D

Pošto se ova greška ponavlja, zanima me samo odakle Vam ideja da zahvat mora imati materijale? Iz SRSa? Iz ER dijagrama?
