### ISSUE TITLE
Moguće unjeti pogrešan datum  i vrijeme u sekciji posjete

### ISSUE THREAD

**Issue by denisdzafo** [SoftverInzenjeringETFSA/SI2014Tim12#71]
Komponenta:
Registracija posjete

Opis problema:
Ukoliko korisnik unese pogršne podatke o datumu ili vremenu, aplikacija dozvoljava kreiranje posjete u prošlosti ili za vrijem koje ne postoji 
Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju prema datom uputstvu unutar projekta;
2. Izvršiti prijavu;
3. Na glavnom izborniku izabrati opciju 'Kreiranje posjete', zatim unjeti datum o prošlosti ili pogrešan tip vremena
4. Kliknuti na dugme 'Registriraj posjetu'

Dobijeni rezultat:
Poruka sa tekstom 'Uspješno dodana posjeta'http://i.imgur.com/sM6kJEW.jpg

Očekivani rezultat:
Obavijest da je neispravan format datuma.

**Comment by EnilPajic** [comment]
Popravljeno, _commit ID:_ b3abe7894309971aba0f6f7d1828c860814f8b18
