### ISSUE TITLE
Moguće unjeti string u sekciji gdje treba integer i obratno

### ISSUE THREAD

**Issue by denisdzafo** [SoftverInzenjeringETFSA/SI2014Tim12#72]
Komponenta:
Kreiraj novog pacijenta

Opis problema:
Ukoliko korisnik u mjestu za koje je predvidjen unos stringa unese integer ili obratno, aplikacija dozvoljava takav unos

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju prema datom uputstvu unutar projekta;
2. Izvršiti prijavu;
3. Na glavnom izborniku izabrati opciju 'Kreiraj novog pacijenta', zatim unesu pogrešni tipovi podatka
4. Kliknuti na dugme 'Kreiraj

Dobijeni rezultat:
Poruka sa tekstom 'Pacijent uspješno dodan' http://i.imgur.com/D6kSskC.jpg

Očekivani rezultat:
Obavijest da nisu uneseni validni podaci.

**Comment by luka454** [comment]
String se može unijeti i u Ime i u telefon i datum i u opis.
Duplicirano #36
