### ISSUE TITLE
Neusaglašenost unosa i pretrage

### ISSUE THREAD

**Issue by denisdzafo** [SoftverInzenjeringETFSA/SI2014Tim12#73]
Komponenta:
Prikaz pacijenta

Opis problema:
Korisnik može pretaživati pacijenta po ID, a nigdje nije ponuđen njegov unos

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju prema datom uputstvu unutar projekta;
2. Izvršiti prijavu;
3. Na glavnom izborniku izabrati opciju 'Prikaz pacijenta', te zatim odabrati pretraživanje po ID-u.

Dobijeni rezultat:
Mogućnost izvršenja te pretrage http://i.imgur.com/FmQbAFn.jpg

Očekivani rezultat:
Prilikom unosa pacijenta, omogučiti unos i njegovog ID.

**Comment by luka454** [comment]
Kolega,

ID dodjeljuje sam sistem, kao i u većini ostalih aplikacija. 
Vjerujem da vam je promaknulo u SRS-u, tamo je točno navedeno koje ulaze prima dodavanje novih pacijenata.
