### ISSUE TITLE
Pretraga termina nije valjana

### ISSUE THREAD

**Issue by denisdzafo** [SoftverInzenjeringETFSA/SI2014Tim12#74]
Komponenta:
Pregled termina

Opis problema:
Ukoliko korisnik ne unese podatke o doktoru, izbacuje se nekozistenta poruka, ni nakon što izađe iz kartice pregled termina.

Koraci za reproduciranje problema:
1. Pokrenuti aplikaciju prema datom uputstvu unutar projekta;
2. Izvršiti prijavu;
3. Na glavnom izborniku izabrati opciju 'Pregled termina' 
4. Kliknuti na dugme 'Pretraži'
5. Izaći iz kartice 'Pregled termina'

Dobijeni rezultat:
Poruka sa tekstom 'Pacijent sa ID-om:0 nije pronadjen' http://i.imgur.com/aMbUUY9.jpg http://i.imgur.com/wHOlj4M.jpg

Očekivani rezultat:
Poruka da se nije unio doktor za traženi termin, i nepojavljivanje obavjesti na početnom meniju.

**Comment by SumejjaPorca** [comment]
Može se pretražiti svi termini od tog i tog datuma ukoliko se ne odabere doktor ili svi termini tog doktora od tog i tog datuma. Sada je ok i to u vezi poruke. Ispravljeno, ne izbacuje više grešku.
