### ISSUE TITLE
Registracija pacijenta 

### ISSUE THREAD

**Issue by deancupovic** [SoftverInzenjeringETFSA/SI2014Tim12#8]
Registracija pacijenta - a gdje je email adresa ako spominjete slanje emailova

**Comment by luka454** [comment]
Ispravljeno, također je dodana i adresa stanovanja

**Comment by luka454** [comment]
Ispravka: radi GUI-a koji je već urađen djelomično, ipak adresa stanovanja nije dodana.

**Comment by deancupovic** [comment]
Otkud sada adresa stanovanja?

**Comment by luka454** [comment]
E ne znam što mi je bilo, ali sam na vrijeme skontao da je nebuloza i uklonio sam prije commita
